<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ExtendFile.Panelis.Application\ExtendFile.Panelis.Application.csproj" />
      <ProjectReference Include="..\ExtendFile.Panelis.Domain\ExtendFile.Panelis.Domain.csproj" />
      <ProjectReference Include="..\ExtendFile.Panelis.Infrastructure\ExtendFile.Panelis.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.24" />
    </ItemGroup>

</Project>
