<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ExtendFile.Panelis.Domain\ExtendFile.Panelis.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ErrorOr" Version="2.0.1" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Modules\Cat\Commands\" />
      <Folder Include="Modules\Cat\Events\" />
      <Folder Include="Modules\Cat\Queries\" />
      <Folder Include="Modules\Cat\Requests\" />
      <Folder Include="Modules\Cat\Responses\" />
      <Folder Include="Modules\Cat\UseCases\" />
      <Folder Include="Modules\Dashboard\Queries\GetDashboard\" />
      <Folder Include="Modules\Dashboard\UseCases\GetDashboard\" />
      <Folder Include="Modules\House\Events\" />
      <Folder Include="Modules\Test\Queries\" />
    </ItemGroup>

</Project>
