<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ExtendFile.Panelis.BuildingBlocks\ExtendFile.Panelis.BuildingBlocks.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Interfaces\Repositories\" />
      <Folder Include="Interfaces\UnitOfWork\" />
    </ItemGroup>

</Project>
